Allow Python setup to fail with warning

diff --git a/python-setup b/python-setup
--- a/python-setup
+++ b/python-setup
@@ -1,9 +1,15 @@
 if python -c 'import sys, tomllib; sys.exit(0 if "dev" in (tomllib.load(open("pyproject.toml", "rb")).get("project", {}).get("dependency-groups", {})) else 1)'; then
-  uv pip install --group dev --system --editable .
-  uv venv
-  uv sync --group dev
+  if ! uv pip install --group dev --system --editable .; then
+    echo "WARNING: Python setup failed!
+  else
+    uv venv
+    uv sync --group dev
+  fi
 else
-  uv pip install --system --editable .
-  uv venv
-  uv sync
+  if ! uv pip install --system --editable .; then
+    echo "WARNING: Python setup failed!
+  else
+    uv venv
+    uv sync
+  fi
 fi
